#!/usr/local/env python3
import google.oauth2.id_token
import google.auth.transport.requests
import httpx


if __name__ == '__main__':
    request = google.auth.transport.requests.Request()
    audience = 'http://localhost:8000'

    id_token = google.oauth2.id_token.fetch_id_token(request, audience)
    headers = {'Authorization': f'bearer {id_token}'}
    print(id_token)
